from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum

class GovernanceSeverity(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"

class RuntimeState(Enum):
    IDLE = "IDLE"                 
    DISPATCHED = "DISPATCHED"     
    THINKING = "THINKING"         
    VALIDATING = "VALIDATING"     
    APPROVED = "APPROVED"         
    ERROR = "ERROR"
    RECOVERY = "RECOVERY"
    HALTED = "HALTED"

@dataclass
class RuntimeTransitionDTO:
    """FSM State Transition DTO for observability."""
    transition_id: str
    timestamp: datetime
    from_state: RuntimeState
    to_state: RuntimeState
    trigger_event: str
    duration_ms: Optional[int] = None

@dataclass
class RuntimeEventDTO:
    """Encapsulates raw event logs for secure UI consumption."""
    event_id: str
    timestamp: datetime
    actor: str
    event_type: str
    severity: GovernanceSeverity
    human_readable_message: str
    payload_preview: Dict[str, Any] = field(default_factory=dict)

@dataclass
class RuntimeHealthSnapshotDTO:
    """System health snapshot generated by HealthService."""
    is_healthy: bool
    current_state: RuntimeState
    rejection_rate: float
    rejection_rate_trend: str     # "UP", "DOWN", "STABLE"
    consecutive_failures: int
    last_critical_violation: Optional[RuntimeEventDTO] = None
    
@dataclass
class RuntimeStateSnapshotDTO:
    """Current FSM and environment snapshot for the UI."""
    task_objective: str
    task_status: str
    active_context_files: List[str]
    recent_transitions: List[RuntimeTransitionDTO] = field(default_factory=list)
