from __future__ import annotations

from pathlib import Path

# Test Inventory Registry mapping all currently tracked test-area Python files to their classifications.
# This registry serves as a guardrail to ensure that only allowed tests are bridged.

TEST_INVENTORY: dict[str, str] = {
    # healthcheck-runner-owned
    "tests/test_full_app_healthcheck_batch_closeout_baseline.py": "healthcheck-runner-owned",
    "tests/test_recommendation_fundamental_filters.py": "service-oracle-recommendation",
    "tests/test_capture_external_evidence_manual_cli.py": "governance-doc-tooling",
    "tests/test_evidence_cadence_review_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_outcome_revision_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_external_evidence_contracts.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_external_evidence_observability_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_experiment_preregistration.py": "governance-doc-tooling",
    "tests/test_ml_oos_exposure_cli.py": "governance-doc-tooling",
    "tests/test_ml_oos_exposure_custody.py": "governance-doc-tooling",
    "tests/test_ml_promotion_review_v2.py": "governance-doc-tooling",
    "tests/test_audit_existing_ooc_calibration.py": "governance-doc-tooling",
    "tests/test_recover_twse_t86_candidate.py": "service-oracle-data-market",
    "tests/test_research_console_dtos.py": "service-oracle-recommendation",
    "tests/test_research_console_source_service.py": "service-oracle-recommendation",
    "tests/test_rule_champion_snapshot_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_source_acceptance_decision_registry.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_source_acceptance_dossier_cli.py": "governance-doc-tooling",
    "tests/test_render_p0_owner_decision_packet.py": "governance-doc-tooling",
    "tests/test_source_acceptance_governance.py": "governance-doc-tooling",
    "tests/test_terra_development_dataset_v0.py": "service-oracle-data-market",
    "tests/test_terra_development_research_cli.py": "governance-doc-tooling",
    "tests/test_terra_development_research_orchestration.py": "governance-doc-tooling",
    "tests/test_build_mops_quarterly_pit_artifact.py": "governance-doc-tooling",
    "tests/test_data_governance_consolidation.py": "service-oracle-data-market",
    "tests/test_fubon_marketdata_research.py": "service-oracle-data-market",
    "tests/test_fubon_readonly_marketdata_probe.py": "service-oracle-data-market",
    "tests/test_inspect_formal_clock_readiness.py": "governance-doc-tooling",
    "tests/test_inspect_ml_formal_input_readiness.py": "governance-doc-tooling",
    "tests/test_inspect_formal_input_candidates.py": "governance-doc-tooling",
    "tests/test_inspect_p0_intake_readiness.py": "governance-doc-tooling",
    "tests/test_append_source_acceptance_decision.py": "governance-doc-tooling",
    "tests/test_inspect_fubon_dossier.py": "governance-doc-tooling",
    "tests/test_fubon_pit_validator.py": "governance-doc-tooling",
    "tests/test_fubon_shadow_authorization.py": "governance-doc-tooling",
    "tests/test_fubon_shadow_decision_service.py": "service-oracle-recommendation",
    "tests/test_inspect_fubon_shadow_decision_cli.py": "governance-doc-tooling",
    "tests/test_official_trading_calendar.py": "service-oracle-data-market",
    "tests/test_official_phase3c_fetcher.py": "service-oracle-data-market",
    "tests/test_ml_direct_chain_maintenance.py": "governance-doc-tooling",
    "tests/test_phase3c_backfill_runner.py": "service-oracle-data-market",
    "tests/test_tdcc_shareholding_historical_boundary.py": "service-oracle-data-market",
    "tests/test_ui_update_view_candidate_status.py": "ui-healthcheck-candidate-bridge",
    "tests/test_fubon_shadow_candidate_repository.py": "service-oracle-data-market",
    "tests/test_audit_test_inventory.py": "governance-doc-tooling",
    "tests/test_run_p0_candidate_audit.py": "governance-doc-tooling",
    "tests/test_run_p0_source_evidence_audit.py": "governance-doc-tooling",
    "tests/test_build_p0_intake_from_audit.py": "governance-doc-tooling",
    "tests/test_qa_technical_indicator_latency.py": "governance-doc-tooling",
    "tests/test_qa_bounded_worker_acceptance.py": "governance-doc-tooling",
    "tests/test_qa_broker_bounded_fetch_acceptance.py": "governance-doc-tooling",
    "tests/test_qa_technical_indicator_process_pool.py": "governance-doc-tooling",
    "tests/test_qa_technical_indicator_worker_recovery.py": "governance-doc-tooling",
    "tests/test_inspect_scheduled_task_registration.py": "governance-doc-tooling",
    "tests/test_tpex_disposal_artifact.py": "service-oracle-data-market",
    "tests/test_validate_mops_quarterly_artifact.py": "governance-doc-tooling",
    "tests/test_twse_t86_candidate_normalizer.py": "service-oracle-data-market",
    "tests/test_twse_t86_candidate_source.py": "service-oracle-data-market",
    "tests/test_ui_qt_research_console_view.py": "ui-healthcheck-candidate-bridge",
    "tests/test_update_service_monthly_revenue_status.py": "service-oracle-data-market",
    "tests/test_technical_indicator_process_pool.py": "service-oracle-data-market",
    "tests/test_full_app_healthcheck_coverage_matrix.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_manifest.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_reporting.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_runner.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_test_suite_bridge.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_test_inventory.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_actions.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_candidate_bridge_policy.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_command_advisor.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_feature_router.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_handoff_contract.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_known_issue_matcher.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_result_interpreter.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_service_oracle_metadata.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_coverage_burndown.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_flow_model.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_flow_diagnostics.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_ux_gap_mapping.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_offscreen_widget_checks.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_mainwindow_smoke_plan.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_viewport_resize_evidence_plan.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_high_risk_dry_run_dialog_plan.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_mainwindow_smoke_runner.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_run_history_manifest.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_run_history_compare.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_quick_mode_release_gate_proposal.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_full_mode_release_checklist.py": "healthcheck-runner-owned",
    "tests/test_full_app_healthcheck_report_sections.py": "healthcheck-runner-owned",

    # ui-healthcheck-direct-bridge
    "tests/test_ui_qt_decision_desk_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_dashboard_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_market_regime_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_research_workflow.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_run_registry_compare.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_smart_money_flow_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_update_view_workbench.py": "ui-healthcheck-direct-bridge",

    # ui-healthcheck-candidate-bridge
    "tests/test_ui_qt_chart_payloads.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_chart_widget_factory.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_decision_desk_main_integration.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_portfolio_condition_monitor.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_portfolio_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_recommendation_next_steps_copy_text.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_recommendation_portfolio_results.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_recommendation_profiles.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_report_export.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_research_lab_mode_driven_ui.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_research_lab_workbench_copy_text.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_research_run_save.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_shutdown_coordinator.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_crash_diagnostics.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_smart_money_flow_async.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_runtime_view.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_session_context_strip.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_theme.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_left_navigation.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_weak_market_views.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_watchlist_candidate_pool_copy_text.py": "ui-healthcheck-direct-bridge",
    "tests/test_ui_qt_workbench_view.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_adaptive_workspace_stack.py": "ui-healthcheck-candidate-bridge",

    # service-oracle-data-market
    "tests/test_abnormal_fundamental_flags.py": "service-oracle-data-market",
    "tests/test_backup_retention.py": "service-oracle-data-market",
    "tests/test_batch_update_market_and_industry_index_import.py": "service-oracle-data-market",
    "tests/test_broker_branch_decode.py": "service-oracle-data-market",
    "tests/test_broker_branch_registry_current_copy.py": "service-oracle-data-market",
    "tests/test_broker_flow_units.py": "service-oracle-data-market",
    "tests/test_broker_flow_dashboard_query_service.py": "service-oracle-data-market",
    "tests/test_broker_flow_sqlite_read_repository.py": "service-oracle-data-market",
    "tests/test_company_registry.py": "service-oracle-data-market",
    "tests/test_corporate_action_availability_history.py": "service-oracle-data-market",
    "tests/test_scheduled_official_market_event_backfill.py": "service-oracle-data-market",
    "tests/test_data_module.py": "service-oracle-data-market",
    "tests/test_db_manager_logging.py": "service-oracle-data-market",
    "tests/test_analysis/test_technical_analysis.py": "service-oracle-data-market",
    "tests/test_finmind_monthly_revenue_create_time.py": "service-oracle-data-market",
    "tests/test_fundamental_availability.py": "service-oracle-data-market",
    "tests/test_fundamental_availability_entrypoint.py": "service-oracle-data-market",
    "tests/test_fundamental_availability_sources.py": "service-oracle-data-market",
    "tests/test_fundamental_data.py": "service-oracle-data-market",
    "tests/test_fundamental_diagnostics_service.py": "service-oracle-data-market",
    "tests/test_fundamental_factor_adapters.py": "service-oracle-data-market",
    "tests/test_fundamental_factor_service.py": "service-oracle-data-market",
    "tests/test_fundamental_schema.py": "service-oracle-data-market",
    "tests/test_fundamental_sqlite_provider.py": "service-oracle-data-market",
    "tests/test_fundamental_statement_availability_entrypoint.py": "service-oracle-data-market",
    "tests/test_fundamental_statement_availability_sources.py": "service-oracle-data-market",
    "tests/test_fundamental_statement_data.py": "service-oracle-data-market",
    "tests/test_market_breadth_service.py": "service-oracle-data-market",
    "tests/test_market_data_visibility_service.py": "service-oracle-data-market",
    "tests/test_market_regime_detector_details.py": "service-oracle-data-market",
    "tests/test_monthly_revenue_availability_builder.py": "service-oracle-data-market",
    "tests/test_monthly_revenue_availability_history.py": "service-oracle-data-market",
    "tests/test_corporate_action_policy.py": "service-oracle-data-market",
    "tests/test_data_source_capability_registry.py": "service-oracle-data-market",
    "tests/test_industry_mapper_performance_cache.py": "service-oracle-data-market",
    "tests/test_relative_strength_liquidity_service.py": "service-oracle-data-market",
    "tests/test_revenue_factor_pack.py": "service-oracle-data-market",
    "tests/test_sector_rotation_service.py": "service-oracle-data-market",
    "tests/test_sqlite_inspector_service.py": "service-oracle-data-market",
    "tests/test_sqlite_storage_compatibility.py": "service-oracle-data-market",
    "tests/test_stock_screener_sqlite_first.py": "service-oracle-data-market",
    "tests/test_source_candidate_readiness.py": "service-oracle-data-market",
    "tests/test_p0_source_control_center.py": "service-oracle-data-market",
    "tests/test_p0_candidate_repository.py": "service-oracle-data-market",
    "tests/test_p0_source_acquisition_routes.py": "service-oracle-data-market",
    "tests/test_p0_ml_eligibility_projection.py": "service-oracle-data-market",
    "tests/test_p0_official_source_parsers.py": "service-oracle-data-market",
    "tests/test_p0_source_candidate_contracts.py": "service-oracle-data-market",
    "tests/test_pit_historical_availability_contracts.py": "service-oracle-data-market",
    "tests/test_pit_historical_coverage_audit.py": "service-oracle-data-market",
    "tests/test_quarterly_statement_availability_history.py": "service-oracle-data-market",
    "tests/test_trading_restriction_policy.py": "service-oracle-data-market",
    "tests/test_decision_market_frame.py": "service-oracle-data-market",
    "tests/test_statement_factor_pack.py": "service-oracle-data-market",
    "tests/test_tpex_background_refresh_script.py": "service-oracle-data-market",
    "tests/test_tpex_daily_price_history_plan.py": "service-oracle-data-market",
    "tests/test_tpex_daily_price_history_plan_cli.py": "service-oracle-data-market",
    "tests/test_update_service_status.py": "service-oracle-data-market",
    "tests/test_valuation_data.py": "service-oracle-data-market",
    "tests/test_valuation_factor_adapters.py": "service-oracle-data-market",
    "tests/test_valuation_policy.py": "service-oracle-data-market",
    "tests/test_valuation_source_policy.py": "service-oracle-data-market",

    # service-oracle-research-backtest
    "tests/test_backtest/test_overfitting_risk.py": "service-oracle-research-backtest",
    "tests/test_backtest/test_parallel_safety.py": "service-oracle-research-backtest",
    "tests/test_backtest_diagnostics_and_date_adjustment.py": "service-oracle-research-backtest",
    "tests/test_backtest_factor_metadata.py": "service-oracle-research-backtest",
    "tests/test_backtest_timeline_contract.py": "service-oracle-research-backtest",
    "tests/test_batch_backtest_research_run_save.py": "service-oracle-research-backtest",
    "tests/test_component_ablation_readiness.py": "service-oracle-research-backtest",
    "tests/test_cross_sectional_factor_attribution.py": "service-oracle-research-backtest",
    "tests/test_cross_sectional_factor_pipeline.py": "service-oracle-research-backtest",
    "tests/test_cross_sectional_factor_repository.py": "service-oracle-research-backtest",
    "tests/test_execution_slippage_model.py": "service-oracle-research-backtest",
    "tests/test_factor_adapters.py": "service-oracle-research-backtest",
    "tests/test_factor_contract.py": "service-oracle-research-backtest",
    "tests/test_factor_gate.py": "service-oracle-research-backtest",
    "tests/test_factor_registry.py": "service-oracle-research-backtest",
    "tests/test_factor_service_research_run.py": "service-oracle-research-backtest",
    "tests/test_inspect_cross_sectional_factor_snapshot_cli.py": "service-oracle-research-backtest",
    "tests/test_ml_readiness_contract.py": "service-oracle-research-backtest",
    "tests/test_pattern_analysis/test_flag_pattern_robustness.py": "service-oracle-research-backtest",
    "tests/test_optimizer_service.py": "service-oracle-research-backtest",
    "tests/test_promotion_reconciliation.py": "service-oracle-research-backtest",
    "tests/test_portfolio_construction_sandbox.py": "service-oracle-research-backtest",
    "tests/test_advice_composer.py": "service-oracle-research-backtest",
    "tests/test_advice_dtos.py": "service-oracle-research-backtest",
    "tests/test_advice_policy.py": "service-oracle-research-backtest",
    "tests/test_collect_v2_2_weekly_evidence_cli.py": "service-oracle-research-backtest",
    "tests/test_evidence_weekly_collection_repository.py": "service-oracle-research-backtest",
    "tests/test_paper_portfolio_baseline_cli.py": "service-oracle-research-backtest",
    "tests/test_paper_portfolio_baseline_service.py": "service-oracle-research-backtest",
    "tests/test_paper_portfolio_policy.py": "service-oracle-research-backtest",
    "tests/test_paper_portfolio_policy_cli.py": "service-oracle-research-backtest",
    "tests/test_position_health_baseline_cli.py": "service-oracle-research-backtest",
    "tests/test_position_health_baseline_service.py": "service-oracle-research-backtest",
    "tests/test_position_health_cli.py": "service-oracle-research-backtest",
    "tests/test_position_health_service.py": "service-oracle-research-backtest",
    "tests/test_workbench_advice_contract.py": "service-oracle-research-backtest",
    "tests/test_portfolio_sandbox_inspection_cli.py": "service-oracle-research-backtest",
    "tests/test_recommendation_portfolio_backtest.py": "service-oracle-research-backtest",
    "tests/test_recommendation_portfolio_optimizer.py": "service-oracle-research-backtest",
    "tests/test_report_export_dtos.py": "service-oracle-research-backtest",
    "tests/test_report_export_service.py": "service-oracle-research-backtest",
    "tests/test_research_lab_mode_taxonomy.py": "service-oracle-research-backtest",
    "tests/test_research_result_presentation.py": "service-oracle-research-backtest",
    "tests/test_research_run_comparison_service.py": "service-oracle-research-backtest",
    "tests/test_research_run_legacy_adapter.py": "service-oracle-research-backtest",
    "tests/test_research_run_repository.py": "service-oracle-research-backtest",
    "tests/test_research_run_service.py": "service-oracle-research-backtest",
    "tests/test_score_threshold_policy.py": "service-oracle-research-backtest",
    "tests/test_score_effectiveness_read_model.py": "service-oracle-research-backtest",
    "tests/test_strategy_lifecycle_repository.py": "service-oracle-research-backtest",
    "tests/test_strategy_lifecycle_service.py": "service-oracle-research-backtest",
    "tests/test_strategy_params_persistence_roundtrip.py": "service-oracle-research-backtest",
    "tests/test_strategy_threshold_modes.py": "service-oracle-research-backtest",
    "tests/test_threshold_robustness_read_model.py": "service-oracle-research-backtest",
    "tests/test_walkforward_service.py": "service-oracle-research-backtest",
    "tests/test_weight_contract.py": "service-oracle-research-backtest",

    # service-oracle-recommendation
    "tests/test_recommendation_dto_roundtrip.py": "service-oracle-recommendation",
    "tests/test_recommendation_percentile_ranker.py": "service-oracle-recommendation",
    "tests/test_profile_replay_comparison_service.py": "service-oracle-recommendation",
    "tests/test_recommendation_evidence_importer.py": "service-oracle-recommendation",
    "tests/test_recommendation_exclusion_payload.py": "service-oracle-recommendation",
    "tests/test_recommendation_portfolio_hints.py": "service-oracle-recommendation",
    "tests/test_recommendation_portfolio_numeric_governance.py": "service-oracle-recommendation",
    "tests/test_recommendation_portfolio_promotion_service.py": "service-oracle-recommendation",
    "tests/test_recommendation_portfolio_run_repository.py": "service-oracle-recommendation",
    "tests/test_recommendation_portfolio_view_charts.py": "service-oracle-recommendation",
    "tests/test_recommendation_profile_service.py": "service-oracle-recommendation",
    "tests/test_recommendation_ranking_service.py": "service-oracle-recommendation",
    "tests/test_recommendation_recomputation.py": "service-oracle-recommendation",
    "tests/test_recommendation_v1_7_negative_evidence.py": "service-oracle-recommendation",

    # service-oracle-portfolio-decision-runtime
    "tests/test_decision_desk_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_builder_factory.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_risk_prompt_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_snapshot_evidence_importer.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_snapshot_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_ui_contract.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_historical_evidence_replay.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_quality_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_quality_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_quality_review_items.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_quality_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_capture_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_event_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_event_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_operations_history_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_operations_history_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_operations_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_pipeline_runner.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_pipeline_scheduler_readiness.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_review_dashboards_no_trading_language.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_scheduler_readiness.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_evidence_source_coverage_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_forward_performance_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_forward_performance_read_model.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_forward_performance_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_live_research_gap_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_live_research_gap_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_live_research_gap_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_live_research_gap_source_matching.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_pre_v2_readiness_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_alert_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_alert_evidence_importer.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_chip_monitor.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_condition_monitor.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_deepening.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_delete.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_feedback_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_jsonl_store_serialization.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_mvp.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_numeric_governance.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_review_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_source_adapter.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_stress_lab_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_paper_portfolio_readiness_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_trade_import_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_smart_money_semantic_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_decision_desk_shared_market_frame.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_v1_9_agent_evidence_access.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_v2_workbench_prototype_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_v3_effectiveness_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_v3_effectiveness_read_model.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_v3_effectiveness_review_scaffold.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_workbench_read_only_composer.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_workbench_replay_summary.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_workbench_source_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_risk_prompt_evidence_importer.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_signal_decay_dashboard_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_signal_decay_lifecycle_payload.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_signal_decay_repository.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_signal_decay_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_watchlist_trigger_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_watchlist_trigger_evidence_importer.py": "service-oracle-portfolio-decision-runtime",

    # governance-doc-tooling
    "tests/test_artifact_lineage_cli.py": "governance-doc-tooling",
    "tests/test_artifact_lineage_verifier.py": "governance-doc-tooling",
    "tests/test_audit_document_encoding.py": "governance-doc-tooling",
    "tests/test_decision_quality_no_trading_language.py": "governance-doc-tooling",
    "tests/test_evidence_pipeline_report.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_adapters.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_cli.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_coverage.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_dtos.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_fault_injection.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_lineage_adapter.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_ml_provider.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_orchestrator.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_source_reader.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_ml_comparison.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_service.py": "governance-doc-tooling",
    "tests/test_evidence_rehearsal_source_comparison.py": "governance-doc-tooling",
    "tests/test_verify_system_execution_blueprint.py": "governance-doc-tooling",
    "tests/test_forward_performance_dashboard_no_trading_language.py": "governance-doc-tooling",
    "tests/test_financial_float_boundary_checker.py": "governance-doc-tooling",
    "tests/test_financial_units.py": "governance-doc-tooling",
    "tests/test_governance_tools.py": "governance-doc-tooling",
    "tests/test_live_research_gap_no_trading_language.py": "governance-doc-tooling",
    "tests/test_mcp_context_server.py": "governance-doc-tooling",
    "tests/test_performance_numeric_governance.py": "governance-doc-tooling",
    "tests/test_production_scheduler_approval_checklist.py": "governance-doc-tooling",
    "tests/test_scheduled_cmd_scripts_exist.py": "governance-doc-tooling",
    "tests/test_scheduled_cmd_scripts_no_confirm.py": "governance-doc-tooling",
    "tests/test_scheduled_ml_raw_pit_refresh.py": "governance-doc-tooling",
    "tests/test_scheduled_ml_direct_chain_maintenance.py": "governance-doc-tooling",
    "tests/test_scheduled_cmd_scripts_task_names.py": "governance-doc-tooling",
    "tests/test_scheduled_data_freshness_probe.py": "governance-doc-tooling",
    "tests/test_scheduled_data_update_runner.py": "governance-doc-tooling",
    "tests/test_scheduled_evidence_pipeline_dry_run_wrapper.py": "governance-doc-tooling",
    "tests/test_scheduled_evidence_status_service.py": "governance-doc-tooling",
    "tests/test_scheduled_readme_no_production_confirm.py": "governance-doc-tooling",
    "tests/test_scheduled_scripts_exist.py": "governance-doc-tooling",
    "tests/test_scheduled_scripts_no_trading_language.py": "governance-doc-tooling",
    "tests/test_scheduled_recommendation_snapshot_wrapper.py": "governance-doc-tooling",
    "tests/test_signal_decay_no_trading_language.py": "governance-doc-tooling",
    "tests/test_pre_v2_readiness_cli.py": "governance-doc-tooling",
    "tests/test_simulated_phase_progress_cli.py": "governance-doc-tooling",
    "tests/test_simulated_phase_progress_service.py": "governance-doc-tooling",
    "tests/test_v3_engineering_candidate_readiness.py": "governance-doc-tooling",
    "tests/test_workbench_read_only_boundary.py": "governance-doc-tooling",
    "tests/test_formal_simulated_portfolio_ledger.py": "governance-doc-tooling",
    "tests/test_process_custody.py": "governance-doc-tooling",
    "tests/test_prospective_activation_environment.py": "governance-doc-tooling",
    "tests/test_prospective_calibration_policy.py": "governance-doc-tooling",
    "tests/test_prospective_capture_readiness.py": "governance-doc-tooling",
    "tests/test_prospective_execution_plan.py": "governance-doc-tooling",
    "tests/test_prospective_formal_activation_once.py": "governance-doc-tooling",
    "tests/test_prospective_formal_clock.py": "governance-doc-tooling",
    "tests/test_prospective_formal_clock_activation.py": "governance-doc-tooling",
    "tests/test_prospective_frozen_oos_evidence.py": "governance-doc-tooling",
    "tests/test_prospective_official_pit_source.py": "governance-doc-tooling",
    "tests/test_prospective_pit_sector_membership.py": "governance-doc-tooling",
    "tests/test_prospective_promotion_review.py": "governance-doc-tooling",
    "tests/test_prospective_rule_champion_publisher.py": "governance-doc-tooling",
    "tests/test_prospective_rule_only_decision.py": "governance-doc-tooling",
    "tests/test_prospective_shadow_maturity.py": "governance-doc-tooling",
    "tests/test_prospective_simulated_ledger_manifest.py": "governance-doc-tooling",
    "tests/test_publish_prospective_formal_clock.py": "governance-doc-tooling",
    "tests/test_ui_qt_evidence_review_dashboards.py": "ui-healthcheck-candidate-bridge",
    "tests/test_ui_qt_forward_performance_view.py": "ui-healthcheck-candidate-bridge",

    # write-risk-dry-run-required
    "tests/test_capture_decision_desk_snapshot_cli.py": "write-risk-dry-run-required",
    "tests/test_capture_evidence_events_cli.py": "write-risk-dry-run-required",
    "tests/test_decision_quality_cli.py": "write-risk-dry-run-required",
    "tests/test_evidence_event_cli.py": "write-risk-dry-run-required",
    "tests/test_evidence_operations_cli.py": "write-risk-dry-run-required",
    "tests/test_evidence_pipeline_smoke.py": "write-risk-dry-run-required",
    "tests/test_evidence_pipeline_working_copy_smoke.py": "write-risk-dry-run-required",
    "tests/test_evidence_source_coverage_cli.py": "write-risk-dry-run-required",
    "tests/test_live_research_gap_cli.py": "write-risk-dry-run-required",
    "tests/test_run_evidence_pipeline_cli.py": "write-risk-dry-run-required",
    "tests/test_signal_decay_cli.py": "write-risk-dry-run-required",
    "tests/test_summarize_forward_performance_cli.py": "write-risk-dry-run-required",
    "tests/scripts/test_all_branches_one_day.py": "write-risk-dry-run-required",
    "tests/scripts/test_broker_branch_10days.py": "write-risk-dry-run-required",
    "tests/scripts/test_broker_branch_single.py": "write-risk-dry-run-required",
    "tests/scripts/test_moneydj_requests.py": "write-risk-dry-run-required",
    "tests/scripts/test_moneydj_requests_tables.py": "write-risk-dry-run-required",
    "tests/test_company_registry_cli.py": "write-risk-dry-run-required",
    "tests/test_finmind_monthly_revenue_create_time_cli.py": "write-risk-dry-run-required",
    "tests/test_fundamental_migration.py": "write-risk-dry-run-required",
    "tests/test_fundamental_migration_cli.py": "write-risk-dry-run-required",
    "tests/test_fundamental_statement_backfill.py": "write-risk-dry-run-required",
    "tests/test_fundamental_statement_backfill_cli.py": "write-risk-dry-run-required",
    "tests/test_inspect_fundamental_factors_cli.py": "write-risk-dry-run-required",
    "tests/test_phase3c_candidate_ingestion.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_availability_builder_cli.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_availability_cli.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_availability_history_cli.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_backfill.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_backfill_cli.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_retroactive_baseline_cli.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_snapshot_harvester.py": "write-risk-dry-run-required",
    "tests/test_monthly_revenue_snapshot_harvester_cli.py": "write-risk-dry-run-required",
    "tests/test_replay_historical_evidence_pipeline_cli.py": "write-risk-dry-run-required",
    "tests/test_statement_availability_cli.py": "write-risk-dry-run-required",
    "tests/test_statement_retroactive_baseline_cli.py": "write-risk-dry-run-required",
    "tests/test_tpex_daily_price_backfill.py": "write-risk-dry-run-required",
    "tests/test_tpex_daily_price_backfill_cli.py": "write-risk-dry-run-required",
    "tests/test_tpex_daily_price_source.py": "write-risk-dry-run-required",
    "tests/test_valuation_metrics_backfill.py": "write-risk-dry-run-required",
    "tests/test_valuation_metrics_backfill_cli.py": "write-risk-dry-run-required",
    "tests/test_valuation_source_policy_cli.py": "write-risk-dry-run-required",

    # slow-e2e-or-environment
    "tests/e2e/test_data_path_isolation.py": "slow-e2e-or-environment",
    "tests/test_cross_workstream_system_integration.py": "slow-e2e-or-environment",
    "tests/test_evidence_rehearsal_real_e2e.py": "slow-e2e-or-environment",

    # manual-only
    "tests/manual/legacy_advanced_patterns_check.py": "manual-only",
    "tests/manual/legacy_api_endpoints_check.py": "manual-only",
    "tests/manual/legacy_daily_data_check.py": "manual-only",
    "tests/manual/legacy_data_loading_check.py": "manual-only",
    "tests/manual/legacy_extended_patterns_check.py": "manual-only",
    "tests/manual/legacy_math_analyzer_check.py": "manual-only",
    "tests/manual/legacy_ml_analyzer_check.py": "manual-only",
    "tests/manual/legacy_optimized_patterns_check.py": "manual-only",
    "tests/manual/legacy_pattern_analyzer_check.py": "manual-only",
    "tests/manual/legacy_pattern_parameter_tuning_check.py": "manual-only",
    "tests/manual/legacy_signal_combiner_check.py": "manual-only",
    "tests/manual/legacy_technical_analyzer_check.py": "manual-only",
    "tests/manual/legacy_twse_api_check.py": "manual-only",
    "tests/manual/legacy_utils_check.py": "manual-only",

    # legacy-or-low-priority (moved candidates mapped to new locations)
    "tests/manual/legacy_diagnostics/run_market_index_test.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/run_technical_calc_test.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/run_tests.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/check_columns.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/check_processed_file.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/check_saved_file.py": "legacy-or-low-priority",
    "tests/manual/legacy_diagnostics/check_signals_file.py": "legacy-or-low-priority",
    "tests/scripts/test_counterparty_parsing.py": "legacy-or-low-priority",
    "tests/test_ml_analysis/__init__.py": "legacy-or-low-priority",
    "tests/test_pattern_analysis/__init__.py": "legacy-or-low-priority",

    # general-unit-keep-in-pytest
    "tests/conftest.py": "general-unit-keep-in-pytest",
    "tests/test_core/test_config.py": "general-unit-keep-in-pytest",
    "tests/test_core/test_data_loader.py": "general-unit-keep-in-pytest",
    "tests/test_indicator_parameter_registry.py": "general-unit-keep-in-pytest",
    "tests/test_m2_a_integration.py": "general-unit-keep-in-pytest",
    "tests/test_derived_market_features.py": "general-unit-keep-in-pytest",
    "tests/test_indicator_reuse.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_execution_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_application_port_annotations.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_optimization_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_report_support.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_research_run_metadata.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_view_presenter.py": "general-unit-keep-in-pytest",
    "tests/test_backtest_walkforward_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_broker_branch_registry_support.py": "general-unit-keep-in-pytest",
    "tests/test_broker_branch_transport_merge_support.py": "general-unit-keep-in-pytest",
    "tests/test_broker_branch_write_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_decision_data_providers.py": "general-unit-keep-in-pytest",
    "tests/test_decision_desk_composition.py": "general-unit-keep-in-pytest",
    "tests/test_decision_desk_dto_contract.py": "general-unit-keep-in-pytest",
    "tests/test_decision_desk_snapshot_support.py": "general-unit-keep-in-pytest",
    "tests/test_decision_service_composition.py": "general-unit-keep-in-pytest",
    "tests/test_evidence_importer_support.py": "general-unit-keep-in-pytest",
    "tests/test_evidence_pipeline_runner_support.py": "general-unit-keep-in-pytest",
    "tests/test_evidence_metric_applicability.py": "general-unit-keep-in-pytest",
    "tests/test_event_price_resolver.py": "general-unit-keep-in-pytest",
    "tests/test_outcome_maturity_service.py": "general-unit-keep-in-pytest",
    "tests/test_p0_source_contract_registry.py": "general-unit-keep-in-pytest",
    "tests/test_p0_corporate_restriction_shadow_adapters.py": "general-unit-keep-in-pytest",
    "tests/test_p0_institutional_flow_shadow_adapter.py": "general-unit-keep-in-pytest",
    "tests/test_p0_credit_transaction_shadow_adapter.py": "general-unit-keep-in-pytest",
    "tests/test_p0_tdcc_distribution_shadow_adapter.py": "general-unit-keep-in-pytest",
    "tests/test_p0_pit_fundamental_announcement_adapters.py": "general-unit-keep-in-pytest",
    "tests/test_p0_source_acceptance_verifier.py": "general-unit-keep-in-pytest",
    "tests/test_p0_source_acceptance_verifier_cli.py": "general-unit-keep-in-pytest",
    "tests/test_paper_portfolio_snapshot_repository.py": "general-unit-keep-in-pytest",
    "tests/test_paper_portfolio_daily_runner.py": "general-unit-keep-in-pytest",
    "tests/test_paper_portfolio_rebalance_evaluator.py": "general-unit-keep-in-pytest",
    "tests/test_paper_equal_weight_benchmark_ledger.py": "general-unit-keep-in-pytest",
    "tests/test_paper_portfolio_weekly_report.py": "general-unit-keep-in-pytest",
    "tests/test_paper_portfolio_weekly_evidence_service.py": "general-unit-keep-in-pytest",
    "tests/test_portfolio_stress_history.py": "general-unit-keep-in-pytest",
    "tests/test_paper_trade_import_service.py": "general-unit-keep-in-pytest",
    "tests/test_paper_trade_ledger.py": "general-unit-keep-in-pytest",
    "tests/test_append_paper_trade_ledger_cli.py": "governance-doc-tooling",
    "tests/test_build_paper_equal_weight_benchmark_cli.py": "governance-doc-tooling",
    "tests/test_inspect_paper_portfolio_weekly_evidence_cli.py": "governance-doc-tooling",
    "tests/test_append_portfolio_stress_history_cli.py": "governance-doc-tooling",
    "tests/test_append_paper_trade_csv_cli.py": "governance-doc-tooling",
    "tests/test_position_thesis_contract.py": "general-unit-keep-in-pytest",
    "tests/test_position_health_state_machine.py": "general-unit-keep-in-pytest",
    "tests/test_position_health_transition_repository.py": "general-unit-keep-in-pytest",
    "tests/test_exit_effectiveness_read_model.py": "general-unit-keep-in-pytest",
    "tests/test_ml_dataset_manifest_registry.py": "general-unit-keep-in-pytest",
    "tests/test_ml_available_date_boundary.py": "general-unit-keep-in-pytest",
    "tests/test_ml_purged_walk_forward.py": "general-unit-keep-in-pytest",
    "tests/test_ml_boosted_challengers.py": "general-unit-keep-in-pytest",
    "tests/test_ml_probability_calibration.py": "general-unit-keep-in-pytest",
    "tests/test_ml_model_prediction_registries.py": "general-unit-keep-in-pytest",
    "tests/test_ml_drift_champion_comparison.py": "general-unit-keep-in-pytest",
    "tests/test_ml_promotion_review_package.py": "general-unit-keep-in-pytest",
    "tests/test_ml_promotion_review_cli.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_dependency_boundary.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_boundary_cli.py": "general-unit-keep-in-pytest",
    "tests/test_ml_2025_locked_oos.py": "general-unit-keep-in-pytest",
    "tests/test_ml_calibration_monitor.py": "general-unit-keep-in-pytest",
    "tests/test_ml_dataset_manifest_v2.py": "general-unit-keep-in-pytest",
    "tests/test_ml_feature_label_registries.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_contracts.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_dataset_builder.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_evaluation.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_feature_builder.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_feature_computation.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_label_builder.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_run_report.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_snapshot_provider.py": "general-unit-keep-in-pytest",
    "tests/test_ml_historical_training_service.py": "general-unit-keep-in-pytest",
    "tests/test_ml_inference_contracts.py": "general-unit-keep-in-pytest",
    "tests/test_ml_model_artifact_loader.py": "general-unit-keep-in-pytest",
    "tests/test_ml_model_artifact_manifest.py": "general-unit-keep-in-pytest",
    "tests/test_ml_model_artifact_store.py": "general-unit-keep-in-pytest",
    "tests/test_ml_model_lifecycle_registry.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_inference_cli.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_inference_service.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_inspect_cli.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_monitoring_service.py": "general-unit-keep-in-pytest",
    "tests/test_ml_shadow_projection_boundary.py": "general-unit-keep-in-pytest",
    "tests/test_ooc_cross_fitted_calibration.py": "general-unit-keep-in-pytest",
    "tests/test_engineering_gate_registry.py": "general-unit-keep-in-pytest",
    "tests/test_ml_revalidation_runbook_service.py": "general-unit-keep-in-pytest",
    "tests/test_ml_revalidation_runbook_cli.py": "general-unit-keep-in-pytest",
    "tests/test_gate_2_to_7_closeout_verifier.py": "general-unit-keep-in-pytest",
    "tests/test_gate_2_to_7_closeout_cli.py": "general-unit-keep-in-pytest",
    "tests/test_engineering_closure_dashboard_service.py": "general-unit-keep-in-pytest",
    "tests/test_engineering_gate_registry_cli.py": "general-unit-keep-in-pytest",
    "tests/test_v3_pruning_decision_service.py": "general-unit-keep-in-pytest",
    "tests/test_v3_pruning_package_cli.py": "general-unit-keep-in-pytest",
    "tests/test_v3_effectiveness_metrics.py": "general-unit-keep-in-pytest",
    "tests/test_flow_contract_ownership.py": "general-unit-keep-in-pytest",
    "tests/test_forward_performance_read_model_support.py": "general-unit-keep-in-pytest",
    "tests/test_indicator_price_kernel.py": "general-unit-keep-in-pytest",
    "tests/test_indicator_registry_dependency_boundary.py": "general-unit-keep-in-pytest",
    "tests/test_industry_mapper_provider.py": "general-unit-keep-in-pytest",
    "tests/test_main_window_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_market_date_utils.py": "general-unit-keep-in-pytest",
    "tests/test_market_regime_data_provider.py": "general-unit-keep-in-pytest",
    "tests/test_market_regime_kernels.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_execution_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_market_data_provider.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_market_frame.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_ranking_pipeline.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_portfolio_result_support.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_run_support.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_save_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_recommendation_view_presenter.py": "general-unit-keep-in-pytest",
    "tests/test_runtime_ui_composition.py": "general-unit-keep-in-pytest",
    "tests/test_runtime_health_service.py": "general-unit-keep-in-pytest",
    "tests/test_runtime_event_cursor.py": "general-unit-keep-in-pytest",
    "tests/test_runtime_event_stream_service.py": "general-unit-keep-in-pytest",
    "tests/test_environment_readiness_service.py": "general-unit-keep-in-pytest",
    "tests/test_inspect_runtime_environment_readiness.py": "governance-doc-tooling",
    "tests/test_scoring_kernels.py": "general-unit-keep-in-pytest",
    "tests/test_stock_screener_provider.py": "general-unit-keep-in-pytest",
    "tests/test_stock_screener_sqlite_reader.py": "general-unit-keep-in-pytest",
    "tests/test_strategy_screening_support.py": "general-unit-keep-in-pytest",
    "tests/test_ui_qt_recommendation_metadata.py": "general-unit-keep-in-pytest",
    "tests/test_ui_qt_task_worker.py": "general-unit-keep-in-pytest",
    "tests/test_ui_thin_shell_boundaries.py": "general-unit-keep-in-pytest",
    "tests/test_update_all_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_update_data_normalization.py": "general-unit-keep-in-pytest",
    "tests/test_update_daily_output.py": "general-unit-keep-in-pytest",
    "tests/test_update_service_import_contract.py": "general-unit-keep-in-pytest",
    "tests/test_update_service_status_support.py": "general-unit-keep-in-pytest",
    "tests/test_update_source_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_update_source_status_projection.py": "general-unit-keep-in-pytest",
    "tests/test_update_status_history.py": "general-unit-keep-in-pytest",
    "tests/test_update_status_timeline.py": "general-unit-keep-in-pytest",
    "tests/test_update_view_formatters.py": "general-unit-keep-in-pytest",
    "tests/test_update_worker_coordinator.py": "general-unit-keep-in-pytest",
    "tests/test_workbench_view_presenter.py": "general-unit-keep-in-pytest",
    "tests/test_analysis/test_signal_analysis_column_support.py": "general-unit-keep-in-pytest",
    "tests/test_analysis/test_technical_column_support.py": "general-unit-keep-in-pytest",
    "tests/test_analysis/test_technical_date_support.py": "general-unit-keep-in-pytest",
    "tests/test_ml_analysis/test_ml_column_support.py": "general-unit-keep-in-pytest",
    "tests/test_pattern_analysis/test_pattern_column_support.py": "general-unit-keep-in-pytest",
    "tests/test_pattern_analysis/test_pattern_fit_support.py": "general-unit-keep-in-pytest",
    "tests/test_pattern_analysis/test_signal_combiner_column_support.py": "general-unit-keep-in-pytest",
    "tests/test_fubon_shadow_feature_mapping.py": "general-unit-keep-in-pytest",
    # V4.0 all-field PIT / allocation ML closeout
    "tests/ml_promotion_test_support.py": "general-unit-keep-in-pytest",
    "tests/test_build_v4_gate_revision_batch.py": "governance-doc-tooling",
    "tests/test_formal_observation_lane.py": "governance-doc-tooling",
    "tests/test_build_ml_pit_year_shards_cli.py": "service-oracle-data-market",
    "tests/test_build_mops_numeric_pit_candidate.py": "service-oracle-data-market",
    "tests/test_development_data_inventory_and_experiments.py": "service-oracle-data-market",
    "tests/test_fetch_mops_daily_research_freshness.py": "service-oracle-data-market",
    "tests/test_inspect_ml_all_field_readiness_cli.py": "service-oracle-data-market",
    "tests/test_ml_all_field_snapshot_provider.py": "service-oracle-data-market",
    "tests/test_ml_file_field_inventory.py": "service-oracle-data-market",
    "tests/test_ml_pit_year_shard_exporter.py": "service-oracle-data-market",
    "tests/test_mops_daily_research_freshness.py": "service-oracle-data-market",
    "tests/test_mops_ezsearch_statement_availability.py": "service-oracle-data-market",
    "tests/test_acquire_mops_numeric_pit_batch.py": "service-oracle-data-market",
    "tests/test_mops_materialization_readiness_gate.py": "service-oracle-data-market",
    "tests/test_mops_numeric_pit_aggregator.py": "service-oracle-data-market",
    "tests/test_mops_source_acceptance_dossier_bridge.py": "service-oracle-data-market",
    "tests/test_manual_rule_only_decision.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_build_ml_allocation_matured_replay_input_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_build_ml_allocation_post_freeze_shadow_input_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_build_portfolio_ml_training_shards_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_daily_ml_allocation_orchestration.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_infer_ml_allocation_copilot_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_contracts.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_copilot.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_inference_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_oos_portfolio_replay.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_promotion_evidence_builder.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_promotion_reference.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_shadow_evidence.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_teacher.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_training_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_allocation_validation.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_formal_portfolio_ledger.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_allocation_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_ml_dataset_assembler.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_ml_out_of_core_pipeline.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_portfolio_turnover.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_promotion_authority_secret_store.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_run_ml_promotion_authority.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_run_ml_promotion_evidence_pipeline.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_continue_ml_direct_ooc_after_store.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_continue_ml_direct_v3_refresh_chain.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_continue_ml_release_after_ooc.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_run_paper_portfolio_daily.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_scheduled_decision_evidence_capture.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_scheduled_operations_service.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_train_ml_allocation_copilot_cli.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_research_shadow_union.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_ml_research_causal_ledger_overlay.py": "service-oracle-portfolio-decision-runtime",
    "tests/test_build_ml_research_shadow_union_cli.py": "service-oracle-portfolio-decision-runtime",
}


PYTEST_SUPPORT_FILES = frozenset(["tests/conftest.py"])

PYTEST_COLLECTED_FILES = frozenset(
    path for path in TEST_INVENTORY
    if path.startswith("tests/")
    and not path.startswith("tests/manual/")
    and not path.startswith("tests/scripts/")
    and Path(path).name.startswith("test_")
    and path.endswith(".py")
)

PYTEST_NOT_COLLECTED_FILES = frozenset(
    path for path in TEST_INVENTORY
    if path not in PYTEST_SUPPORT_FILES and path not in PYTEST_COLLECTED_FILES
)

BRIDGE_REJECTED_CATEGORIES = frozenset([
    "healthcheck-runner-owned",
    "service-oracle-data-market",
    "service-oracle-research-backtest",
    "service-oracle-recommendation",
    "service-oracle-portfolio-decision-runtime",
    "governance-doc-tooling",
    "write-risk-dry-run-required",
    "slow-e2e-or-environment",
    "manual-only",
    "legacy-or-low-priority",
    "general-unit-keep-in-pytest",
])


def get_all_test_files() -> frozenset[str]:
    return frozenset(TEST_INVENTORY.keys())


def get_category(path: str) -> str | None:
    norm_path = path.replace("\\", "/")
    return TEST_INVENTORY.get(norm_path)


def is_allowed_in_bridge(path: str) -> bool:
    category = get_category(path)
    return category == "ui-healthcheck-direct-bridge"


def get_direct_bridge_files() -> frozenset[str]:
    return frozenset(path for path, cat in TEST_INVENTORY.items() if cat == "ui-healthcheck-direct-bridge")


def get_candidate_bridge_files() -> frozenset[str]:
    return frozenset(path for path, cat in TEST_INVENTORY.items() if cat == "ui-healthcheck-candidate-bridge")


def get_bridge_rejected_files() -> frozenset[str]:
    return frozenset(path for path, cat in TEST_INVENTORY.items() if cat in BRIDGE_REJECTED_CATEGORIES)


def is_collected_by_default_pytest(path: str) -> bool:
    return path in PYTEST_COLLECTED_FILES


def get_pytest_collection_status(path: str) -> str:
    if path not in TEST_INVENTORY:
        return "unknown"
    if path in PYTEST_COLLECTED_FILES:
        return "collected"
    if path in PYTEST_SUPPORT_FILES:
        return "support"
    return "not-collected"


def get_files_by_category(category: str) -> frozenset[str]:
    return frozenset(path for path, cat in TEST_INVENTORY.items() if cat == category)


def get_reject_reason(path: str) -> str | None:
    category = get_category(path)
    if category is None:
        return f"未登錄或未分類的測試檔案：{path}"

    if category == "ui-healthcheck-direct-bridge":
        return None

    reasons = {
        "healthcheck-runner-owned": "健康檢查框架自身的單元測試，不可由 runner 調用自身以防無窮迴圈。",
        "ui-healthcheck-candidate-bridge": "屬於候選橋接測試，第一版尚未完成安全防護，目前不允許橋接。",
        "service-oracle-data-market": "屬於數據與市場 Oracle，不應直接作為 UI Flow 步驟執行。",
        "service-oracle-research-backtest": "屬於研究與回測 Oracle，不屬 UI 導覽步驟。",
        "service-oracle-recommendation": "屬於推薦系統 Oracle，不屬 UI 導覽步驟。",
        "service-oracle-portfolio-decision-runtime": "屬於持倉、每日決策與 Runtime Oracle，不屬 UI 導覽步驟。",
        "governance-doc-tooling": "屬於輔助治理工具，非 UI 驗證主流程。",
        "write-risk-dry-run-required": "此測試包含資料寫入風險，預設禁止由非破壞式 runner 執行。",
        "slow-e2e-or-environment": "屬於慢速 E2E 或特定環境測試，禁止於 quick/full bridge 執行。",
        "manual-only": "屬於歷史探索或人工驗證腳本，禁止由自動化 runner 執行。",
        "legacy-or-low-priority": "屬於遺留或低優先級診斷腳本，禁止執行。",
        "general-unit-keep-in-pytest": "屬於通用單元測試，應保留在一般 pytest 流程中獨立執行。",
    }

    return reasons.get(category, f"此分類 ({category}) 禁止執行於 runner bridge。")
