"""Record one explicit human position-thesis version into a derived registry."""

from __future__ import annotations

import argparse
from datetime import datetime
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_module.position_health_source_providers import (  # noqa: E402
    PositionThesisRegistryWriter,
)
from app_module.position_thesis_contract import (  # noqa: E402
    PositionInvalidationRule,
    PositionThesisContract,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Append an explicit human-authored position thesis. "
            "No investment rationale is generated by this command."
        )
    )
    parser.add_argument("--registry", required=True, help="derived thesis registry JSON path")
    parser.add_argument("--position-id", required=True, help="stable position identity")
    parser.add_argument("--entry-lineage-id", required=True, help="stable entry lineage identity")
    parser.add_argument("--stock-code", required=True)
    parser.add_argument("--entry-date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--decision-date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--available-date", required=True, help="YYYY-MM-DD")
    parser.add_argument("--available-at", required=True, help="timezone-aware ISO timestamp")
    parser.add_argument("--authored-at", required=True, help="timezone-aware ISO timestamp")
    parser.add_argument("--authored-by", required=True, help="reviewer identity")
    parser.add_argument("--entry-thesis", required=True, help="explicit human thesis text")
    parser.add_argument("--holding-horizon-trading-days", required=True, type=int)
    parser.add_argument("--next-review-date", required=True, help="YYYY-MM-DD")
    parser.add_argument(
        "--source-trace",
        action="append",
        required=True,
        help="repeat for each source trace entry",
    )
    parser.add_argument(
        "--invalidation-rules",
        required=True,
        help=(
            "JSON array; each item has metric_id, operator, Decimal threshold text, "
            "and action reduce|exit"
        ),
    )
    parser.add_argument("--version-id", required=True, help="immutable registry version identity")
    return parser


def _parse_rules(value: str) -> tuple[PositionInvalidationRule, ...]:
    raw = json.loads(value)
    if not isinstance(raw, list) or not raw:
        raise ValueError("--invalidation-rules must be a non-empty JSON array")
    rules: list[PositionInvalidationRule] = []
    from decimal import Decimal

    for item in raw:
        if not isinstance(item, dict):
            raise ValueError("each invalidation rule must be an object")
        threshold = item.get("threshold")
        if not isinstance(threshold, str):
            raise ValueError("invalidation threshold must be Decimal text")
        rules.append(
            PositionInvalidationRule(
                metric_id=str(item.get("metric_id") or ""),
                operator=str(item.get("operator") or ""),
                threshold=Decimal(threshold),
                action=str(item.get("action") or "exit"),
            )
        )
    return tuple(rules)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        contract = PositionThesisContract(
            position_id=args.position_id,
            stock_code=args.stock_code,
            entry_date=args.entry_date,
            decision_date=args.decision_date,
            available_date=args.available_date,
            entry_thesis=args.entry_thesis,
            holding_horizon_trading_days=args.holding_horizon_trading_days,
            next_review_date=args.next_review_date,
            source_trace=tuple(args.source_trace),
            invalidation_rules=_parse_rules(args.invalidation_rules),
        )
        result = PositionThesisRegistryWriter(args.registry).append(
            contract=contract,
            entry_lineage_id=args.entry_lineage_id,
            version_id=args.version_id,
            authored_by=args.authored_by,
            authored_at=args.authored_at,
            available_at=args.available_at,
        )
    except (OSError, TypeError, ValueError, json.JSONDecodeError) as exc:
        print(
            json.dumps(
                {
                    "status": "blocked",
                    "error": f"{type(exc).__name__}:{exc}",
                    "research_only": True,
                    "auto_action_allowed": False,
                },
                ensure_ascii=False,
                sort_keys=True,
                indent=2,
            )
        )
        return 2
    print(json.dumps(result, ensure_ascii=False, sort_keys=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
